### ISSUE TITLE
Lack a vignette or README to teach users to extract signatures and refit mutation catalogs.

### ISSUE THREAD

**Issue by WuyangFF95** [dami82/mutSignatures#1]
Hi @dami82 ,

I'd like to use your package, but I cannot find a vignette, or an instructive README to teach me how to use the package to extract signatures and refit mutation catalogs with signature. Can you post a vignette or README onto the package? Thanks!

**Comment by dami82** [comment]
Dear Yang,

thanks for your interest in my R library. I understand your frustration
about the lack of a vignette or a README describing how to use the package.
We wanted to submit a small paper describing this library for publication
(the function help is the last thing still missing) , but my PI
de-prioritized the whole project lately (we should get back on track in a
month or so).
In the meanwhile, please find these 3 vignettes, these should help you
getting started. Don't hesitate to contact me with questions.

Best regards.
Damiano


Il giorno mer 7 ago 2019 alle ore 03:44 Wu,Yang <notifications@github.com>
ha scritto:

**Comment by WuyangFF95** [comment]
Good luck on your paper!

I still cannot find the vignettes, but you don't need to worry about that right now. I'll try to figure out running by myself, and if you have uploaded the vignettes, please tell me.

Thanks much!

**Comment by dami82** [comment]
They were attached to my previous email as PDF files.

Best regards,
Damiano

——
Damiano Fantini

**Comment by dami82** [comment]
do you mind sending me an 
email to my address: dami DOT fantini AT gmail DOT com? Thanks

Best regards,
Damiano

——
Damiano Fantini

**Comment by WuyangFF95** [comment]
Sure! I've sent you my email address.
