### ISSUE TITLE
organism slotname missing from BSgenome breaks vignette

### ISSUE THREAD

**Issue by stu2** [dami82/mutSignatures#11]
Hi,

As far as I can see there is no slotname "organism" in `BSgenome.Hsapiens.UCSC.hg19` in bioconductor3.13.
This breaks the vignette example when using attachContext.addON() internal function, lines #29 and #69.

Cheers,

Stuart

**Comment by dami82** [comment]
Hi Stuart,

Sorry about the issue you experienced, but I am confused...
Are you using/testing the CRAN version of mutSignatures but commenting here on the devel version available on GitHub?

Please, can you make sure you have the latest (GitHub) version installed on your system and then try running the same example again? Appreciated!

If the error persists, I will address it...

Best regards,
Damiano

——
Damiano Fantini

**Comment by stu2** [comment]
Hi Damiano,

Sorry you are right. I was using the CRAN version. This dev version works fine. I'm closing this issue.

Best,

Stuart
