### ISSUE TITLE
attachContext(): an error has occoured from the vignette example

### ISSUE THREAD

**Issue by arteteco** [dami82/mutSignatures#13]
Hi all,
I'm trying to test this package by using the documentation examples. Now I'm trying the very first command in the [getting started guide](https://cran.r-project.org/web/packages/mutSignatures/vignettes/get_sarted_with_mutSignatures.html), so this is the code I'm running

```
# Required libs
library(dplyr)
library(reshape2)
library(kableExtra)
library(ggplot2)
library(gridExtra)
library(BSgenome.Hsapiens.UCSC.hg19)

# Load mutSignatures
library(mutSignatures)

# prep hg19
hg19 <- BSgenome.Hsapiens.UCSC.hg19

# load data
data("mutSigData")

# Import data (VCF-like format)
x <- mutSigData$inputC

# Filter non SNV
x <- filterSNV(dataSet = x,  seq_colNames = c("REF", "ALT"))

# Visualize head
head(x) %>% kable() %>% kable_styling(bootstrap_options = "striped")
```

So far so good, x seems correct with all the right columns and all

```
  CHROM       POS ID REF ALT   QUAL FILTER INFO FORMAT XTR1       SAMPLEID
1 chr15  73624589  .   G   T 29.084      .    .  GT:PL  0/1 BLCA.001103810
2 chr22  35684398  .   G   A 21.995      .    .  GT:PL  0/1 BLCA.001103810
3  chr3 183689484  .   G   A 27.296      .    .  GT:PL  0/1 BLCA.001103810
4 chr16  89261395  .   G   A 24.398      .    .  GT:PL  0/1 BLCA.001103810
5 chr19  44662014  .   G   C 21.626      .    .  GT:PL  0/1 BLCA.001103810
6 chr16  30724634  .   G   C 38.741      .    .  GT:PL  0/1 BLCA.001103810
```

But when I give the next command I have an error

```
> # Attach context
> x <- attachContext(mutData = x,
+                    chr_colName = "CHROM",
+                    start_colName = "POS",
+                    end_colName = "POS",
+                    nucl_contextN = 3,
+                    BSGenomeDb = hg19)
An error has occurred!
```

And x has value `NULL`

Any idea what's happening here?

Thanks!

**Comment by dami82** [comment]
Hello,

please, make sure you have the latest version of the mutSignatures library (from GitHub, NOT from CRAN) installed on your system. Please, attach a SessionInfo to the message, it will help me reproducing the environment that returned this error. I'll look into this within few days.

Best regards,
Damiano

——
Damiano Fantini

**Comment by arteteco** [comment]
Thank you @dami82 , it was a version error, I was using the cran one (2.1.1), after installing the github one the error was no more.
I apologise, should have checked that sooner!

**Comment by dami82** [comment]
Dear Manuel,

Thanks for looking into this and closing the issue.
I am glad that the latest version of *mutSignatures *is working as expected
and returning no more errors.
Don't hesitate to email me any further questions/comments.

Best regards,
Damiano
