### ISSUE TITLE
How to cite mutSignatures?

### ISSUE THREAD

**Issue by WuyangFF95** [dami82/mutSignatures#2]
Dear @dami82,

I'm writing a manuscript involving your software package, and I plan to finish it by next month.

Can you tell me how to cite mutSignatures? Is it okay for me to cite your GitHub repository link?

Thanks!
Yang

**Comment by dami82** [comment]
Dear Yang,

Happy new year and sorry for my late reply.
Thanks for using *mutSignatures*. I am glad you are getting close to
publish your research. Also, I hope you found my software useful for your
research, as well as reliable and easy to use.
Unfortunately, I do not have a *mutSignatures*-dedicated publication for
you to cite yet. We are still trying to push a paper describing the package
out. Unfortunately, despite the manuscript being ready, this has been
de-prioritized as I recently moved to a new role. I'll keep you posted if
we release a biorxiv (or similar) in the next few months. In the meanwhile,
I agree with you about the GitHub link. Also, you may want to cite the
paper where I first made use of mutSignatures: Oncogene.
<https://www.ncbi.nlm.nih.gov/pubmed/29367767#> 2018 Apr;37(14):1911-1925.
doi: 10.1038/s41388-017-0099-6
This is the first paper where the mutSignatures package was extensively
used (and discussed). Maybe, you could add a line in the materials and
methods section stating:

*[...] mutational signatures were computed using mutSignatures
(https://github.com/dami82/mutSignatures
<https://github.com/dami82/mutSignatures>) as shown before [Oncogene. 2018
Apr;37(14):1911-1925] [...], *

or something similar.

Again, thank you for using *mutSignatures*.

Best regards,
Damiano








Il giorno lun 30 dic 2019 alle ore 05:17 Wu,Yang <notifications@github.com>
ha scritto:

**Comment by WuyangFF95** [comment]
Thank you Damiano!

I made an assessment on a number of software packages on mutational signature analysis. And you package is the best! I'll send you the manuscript once it is accepted.
