### ISSUE TITLE
attachContext error

### ISSUE THREAD

**Issue by edmundc612** [dami82/mutSignatures#9]
I tried using mutSignatures by following the steps in this link https://cran.r-project.org/web/packages/mutSignatures/vignettes/get_sarted_with_mutSignatures.html

I followed all the steps closely but when I tired to use the attachContext function, an error message poped out. May I know how to resolve the issue?
<img width="632" alt="Screenshot 2021-05-26 at 3 43 35 PM" src="https://user-images.githubusercontent.com/81181464/119621815-23ebc780-be39-11eb-8940-32d013a8c143.png">

**Comment by dami82** [comment]
Hello Edmundc612, 

Thanks for using `mutSignatures` and for your inquiry. Please note that the structure of `BSgenomeDb` objects has changed in the current version of `bioc`. I have updated the `attachContext()` function code accordingly. These changes are implemented in the `dev` version of mutSignatures (available here on GitHub but NOT on CRAN yet).
Are you using the GitHub or CRAN version of the package? Please, can you make sure you have the GitHub version installed in your system?
```
devtools::install_github("dami82/mutSignatures", force = TRUE, build_vignettes = TRUE)
```
Please, reinstall and/or update your *bioc* packages (if necessary), re-start R and then try again. Let me know if this helps.
Also, it may be useful to paste a `SessionInfo()` output next time. 

Best regards.
DF

**Comment by edmundc612** [comment]
Yes this worked, thanks a lot.
